---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multiprox-operator
  namespace: multiprox-system
  labels:
    app.kubernetes.io/name: multiprox-operator
    app.kubernetes.io/component: controller
