//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Re-generate with: controller-gen object paths="./..."

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ─────────────────────────────────────────────────────────────────────────────
// ProxmoxCluster
// ─────────────────────────────────────────────────────────────────────────────

func (in *ProxmoxCluster) DeepCopyInto(out *ProxmoxCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ProxmoxCluster) DeepCopy() *ProxmoxCluster {
	if in == nil {
		return nil
	}
	out := new(ProxmoxCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *ProxmoxCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ProxmoxClusterList) DeepCopyInto(out *ProxmoxClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		i, o := &in.Items, &out.Items
		*o = make([]ProxmoxCluster, len(*i))
		for idx := range *i {
			(*i)[idx].DeepCopyInto(&(*o)[idx])
		}
	}
}

func (in *ProxmoxClusterList) DeepCopy() *ProxmoxClusterList {
	if in == nil {
		return nil
	}
	out := new(ProxmoxClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *ProxmoxClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Spec
// ─────────────────────────────────────────────────────────────────────────────

func (in *ProxmoxClusterSpec) DeepCopyInto(out *ProxmoxClusterSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.Storage.DeepCopyInto(&out.Storage)
	out.Corosync = in.Corosync
	if in.Ceph != nil {
		o := new(CephSpec)
		in.Ceph.DeepCopyInto(o)
		out.Ceph = o
	}
	if in.ImagePullSecrets != nil {
		i, o := &in.ImagePullSecrets, &out.ImagePullSecrets
		*o = make([]corev1.LocalObjectReference, len(*i))
		copy(*o, *i)
	}
	if in.NodeSelector != nil {
		i, o := &in.NodeSelector, &out.NodeSelector
		*o = make(map[string]string, len(*i))
		for k, v := range *i {
			(*o)[k] = v
		}
	}
	if in.Tolerations != nil {
		i, o := &in.Tolerations, &out.Tolerations
		*o = make([]corev1.Toleration, len(*i))
		for idx := range *i {
			(*i)[idx].DeepCopyInto(&(*o)[idx])
		}
	}
	if in.Affinity != nil {
		o := new(corev1.Affinity)
		in.Affinity.DeepCopyInto(o)
		out.Affinity = o
	}
}

func (in *ProxmoxClusterSpec) DeepCopy() *ProxmoxClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ProxmoxClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	in.ClusterData.DeepCopyInto(&out.ClusterData)
	in.VMStorage.DeepCopyInto(&out.VMStorage)
}

func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PVCSpec) DeepCopyInto(out *PVCSpec) {
	*out = *in
	if in.StorageClass != nil {
		sc := *in.StorageClass
		out.StorageClass = &sc
	}
}

func (in *PVCSpec) DeepCopy() *PVCSpec {
	if in == nil {
		return nil
	}
	out := new(PVCSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CorosyncSpec) DeepCopyInto(out *CorosyncSpec) { *out = *in }

func (in *CorosyncSpec) DeepCopy() *CorosyncSpec {
	if in == nil {
		return nil
	}
	out := new(CorosyncSpec)
	in.DeepCopyInto(out)
	return out
}

// ─────────────────────────────────────────────────────────────────────────────
// Ceph
// ─────────────────────────────────────────────────────────────────────────────

func (in *CephSpec) DeepCopyInto(out *CephSpec) {
	*out = *in
	if in.OSDStorageClass != nil {
		sc := *in.OSDStorageClass
		out.OSDStorageClass = &sc
	}
	if in.Pools != nil {
		i, o := &in.Pools, &out.Pools
		*o = make([]CephPoolSpec, len(*i))
		for idx := range *i {
			(*i)[idx].DeepCopyInto(&(*o)[idx])
		}
	}
}

func (in *CephSpec) DeepCopy() *CephSpec {
	if in == nil {
		return nil
	}
	out := new(CephSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CephPoolSpec) DeepCopyInto(out *CephPoolSpec) {
	*out = *in
	if in.Content != nil {
		i, o := &in.Content, &out.Content
		*o = make([]string, len(*i))
		copy(*o, *i)
	}
	if in.AddAsStorage != nil {
		b := *in.AddAsStorage
		out.AddAsStorage = &b
	}
}

func (in *CephPoolSpec) DeepCopy() *CephPoolSpec {
	if in == nil {
		return nil
	}
	out := new(CephPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// ─────────────────────────────────────────────────────────────────────────────
// Status
// ─────────────────────────────────────────────────────────────────────────────

func (in *ProxmoxClusterStatus) DeepCopyInto(out *ProxmoxClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		i, o := &in.Conditions, &out.Conditions
		*o = make([]v1.Condition, len(*i))
		for idx := range *i {
			(*i)[idx].DeepCopyInto(&(*o)[idx])
		}
	}
	if in.Ceph != nil {
		o := new(CephStatus)
		in.Ceph.DeepCopyInto(o)
		out.Ceph = o
	}
}

func (in *ProxmoxClusterStatus) DeepCopy() *ProxmoxClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ProxmoxClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *CephStatus) DeepCopyInto(out *CephStatus) {
	*out = *in
	if in.Monitors != nil {
		i, o := &in.Monitors, &out.Monitors
		*o = make([]string, len(*i))
		copy(*o, *i)
	}
	if in.Managers != nil {
		i, o := &in.Managers, &out.Managers
		*o = make([]string, len(*i))
		copy(*o, *i)
	}
	if in.Pools != nil {
		i, o := &in.Pools, &out.Pools
		*o = make([]string, len(*i))
		copy(*o, *i)
	}
}

func (in *CephStatus) DeepCopy() *CephStatus {
	if in == nil {
		return nil
	}
	out := new(CephStatus)
	in.DeepCopyInto(out)
	return out
}

// ─────────────────────────────────────────────────────────────────────────────
// ProxmoxNode
// ─────────────────────────────────────────────────────────────────────────────

func (in *ProxmoxNode) DeepCopyInto(out *ProxmoxNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ProxmoxNode) DeepCopy() *ProxmoxNode {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNode)
	in.DeepCopyInto(out)
	return out
}

func (in *ProxmoxNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ProxmoxNodeList) DeepCopyInto(out *ProxmoxNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		i, o := &in.Items, &out.Items
		*o = make([]ProxmoxNode, len(*i))
		for idx := range *i {
			(*i)[idx].DeepCopyInto(&(*o)[idx])
		}
	}
}

func (in *ProxmoxNodeList) DeepCopy() *ProxmoxNodeList {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNodeList)
	in.DeepCopyInto(out)
	return out
}

func (in *ProxmoxNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ProxmoxNodeSpec) DeepCopyInto(out *ProxmoxNodeSpec) { *out = *in }

func (in *ProxmoxNodeSpec) DeepCopy() *ProxmoxNodeSpec {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNodeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ProxmoxNodeStatus) DeepCopyInto(out *ProxmoxNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		i, o := &in.Conditions, &out.Conditions
		*o = make([]v1.Condition, len(*i))
		for idx := range *i {
			(*i)[idx].DeepCopyInto(&(*o)[idx])
		}
	}
	if in.Ceph != nil {
		o := new(ProxmoxNodeCephStatus)
		in.Ceph.DeepCopyInto(o)
		out.Ceph = o
	}
	if in.ObservedAt != nil {
		t := in.ObservedAt.DeepCopy()
		out.ObservedAt = t
	}
}

func (in *ProxmoxNodeStatus) DeepCopy() *ProxmoxNodeStatus {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNodeStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ProxmoxNodeCephStatus) DeepCopyInto(out *ProxmoxNodeCephStatus) {
	*out = *in
	if in.Devices != nil {
		i, o := &in.Devices, &out.Devices
		*o = make([]string, len(*i))
		copy(*o, *i)
	}
}

func (in *ProxmoxNodeCephStatus) DeepCopy() *ProxmoxNodeCephStatus {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNodeCephStatus)
	in.DeepCopyInto(out)
	return out
}
