#!/usr/bin/env bash
##############################################################################
# gen-scale.sh — emit a compose override defining PVE nodes 4..N.
#
#   ./gen-scale.sh 11 > docker-compose.scale.yml
#   docker compose -f docker-compose.yml -f docker-compose.scale.yml up -d
#
# Why not `extends:` from pve3
# ---------------------------
# The previous generator used `extends: {file: docker-compose.yml, service: pve3}`,
# which inherits pve3's volume list. Every generated node then had to override it,
# and the override was written before the cluster was ever run for real — so it
# still emitted the /sys/fs/cgroup bind mount (which prevents systemd from
# booting at all under cgroup v2) and lacked the /etc/corosync, /var/lib/ceph and
# /run/udev entries that were later found to be required.
#
# Full service definitions are emitted instead: what you read is what runs, and
# there is one place to keep in step with docker-compose.yml.
#
# Node N gets:
#   IP        10.10.0.(10+N)   management: Corosync, Ceph, pmxcfs, web UI
#   guest IP  10.20.0.(10+N)   second NIC, enslaved to vmbr0 by setup-bridge.sh
#   UI port   8005+N
#   SSH port  22200+N      (matching the 22201-22203 scheme of the base file;
#                           deliberately clear of 2222, a common host sshd port)
##############################################################################

set -euo pipefail

N="${1:-}"

if ! [[ "$N" =~ ^[0-9]+$ ]] || [ "$N" -lt 4 ]; then
    echo "usage: $0 <total-nodes>   (must be >= 4)" >&2
    exit 1
fi

# 10.10.0.0/24 with .1 as the gateway; node 1 starts at .11.
if [ "$N" -gt 240 ]; then
    echo "error: $N nodes exceeds the 10.10.0.0/24 subnet. Widen the network in" >&2
    echo "       docker-compose.yml before going this large." >&2
    exit 1
fi

cat <<HEADER
# Generated by scripts/gen-scale.sh $N — do not edit by hand.
# Regenerate with: make scale N=$N
#
# Defines PVE nodes 4..$N. Use alongside the base file:
#   docker compose -f docker-compose.yml -f docker-compose.scale.yml up -d

services:
HEADER

for i in $(seq 4 "$N"); do
    ip="10.10.0.$(( 10 + i ))"
    guest_ip="10.20.0.$(( 10 + i ))"
    ui="$(( 8005 + i ))"
    ssh_port="$(( 22200 + i ))"

    cat <<SERVICE

  pve${i}:
    image: multiprox-node:trixie
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_CEPH: "1"
    container_name: multiprox-pve${i}
    hostname: pve${i}.multiprox.local
    privileged: true
    # systemd needs its own cgroup root; bind-mounting the host hierarchy
    # shadows it and PID 1 exits 255.
    cgroup: private
    # corosync's libqb exhausts Docker's 64 MB default.
    shm_size: 1gb
    devices:
      # pmxcfs mounts /etc/pve through FUSE.
      - /dev/fuse:/dev/fuse
    tmpfs:
      - /tmp:mode=1777
      - /run:mode=755
      - /run/lock:mode=1777
    networks:
      proxmox-net:
        ipv4_address: ${ip}
      # Bridged into vmbr0 by setup-bridge.sh; shared L2 for guests.
      guest-net:
        ipv4_address: ${guest_ip}
    ports:
      - "\${PVE${i}_UI_PORT:-${ui}}:8006"
      - "\${PVE${i}_SSH_PORT:-${ssh_port}}:22"
    volumes:
      # No /run/udev bind mount: it would block the node's own udevd, which
      # rbd map depends on. See docker-compose.yml for the full reason.
      # (No backticks in this heredoc — it is unquoted so that \${ip} expands,
      # which means backticks would run as command substitution.)
      - pve${i}-cluster:/var/lib/pve-cluster
      # corosync authkey lives here and is NOT in pmxcfs; losing it stops
      # corosync from starting after a container is recreated.
      - pve${i}-corosync:/etc/corosync
      # ceph mon/mgr/osd state, likewise outside pmxcfs.
      - pve${i}-ceph:/var/lib/ceph
      - pve${i}-storage:/var/lib/vz
      - pve${i}-logs:/var/log/pve
    environment:
      NODE_NAME: pve${i}
      NODE_IP: ${ip}
      NODE_ID: ${i}
      CLUSTER_NAME: \${CLUSTER_NAME:-multiprox}
      NODE1_IP: \${NODE1_IP:-10.10.0.11}
      ROOT_PASSWORD: \${ROOT_PASSWORD:-proxmox}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsk", "https://localhost:8006"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      - pve1
SERVICE
done

echo ""
echo "volumes:"
for i in $(seq 4 "$N"); do
    printf '  pve%s-cluster:\n  pve%s-corosync:\n  pve%s-ceph:\n  pve%s-storage:\n  pve%s-logs:\n' \
        "$i" "$i" "$i" "$i" "$i"
done
