#!/usr/bin/env bash
##############################################################################
# gen-ceph.sh — emit the Ceph overlay: N nodes x M loop-backed OSD devices.
#
#   ./gen-ceph.sh 11 3 > docker-compose.ceph.yml
#
# Pairs with setup-loop-osds.sh, which creates the loop devices on the host and
# exposes them as stable symlinks:
#
#   /dev/multiprox/osd-<node>-<index>   ->   /dev/loopN
#
# Each node receives its M devices as /dev/ceph-osd-0 .. /dev/ceph-osd-(M-1),
# so every node sees an identical layout no matter which loop devices the
# kernel happened to hand out.
#
# Loop devices rather than physical disks, deliberately: a host has a handful of
# spare disks at most, which would cap the cluster at that many OSDs however
# many PVE nodes are running. Loop devices scale with the node count, so an
# 11-node cluster gets a full 33-OSD Ceph cluster and real CRUSH placement
# across 11 failure domains.
#
# The symlink indirection matters: kernel loop numbering is not stable across
# reboots, and setup-loop-osds.sh re-points the symlinks when it re-attaches.
# The compose file never names /dev/loopN directly.
##############################################################################

set -euo pipefail

NODES="${1:-}"
PER_NODE="${2:-3}"
LINKDIR="${LINKDIR:-/dev/multiprox}"

if ! [[ "$NODES" =~ ^[0-9]+$ ]] || [ "$NODES" -lt 1 ]; then
    echo "usage: $0 <nodes> [osds-per-node]" >&2
    exit 1
fi

cat <<HEADER
# Generated by scripts/gen-ceph.sh $NODES $PER_NODE — do not edit by hand.
#
# $NODES nodes x $PER_NODE OSD devices = $(( NODES * PER_NODE )) OSDs.
#
# Requires the loop devices to exist first:
#   sudo ./scripts/setup-loop-osds.sh $NODES $PER_NODE 8G
#
# Then:
#   docker compose -f docker-compose.yml -f docker-compose.scale.yml \\
#                  -f docker-compose.ceph.yml up -d
#   make ceph-full
#
# NOTE: \`devices:\` REPLACES the base list rather than merging, so /dev/fuse is
# repeated for every node — without it pmxcfs cannot mount /etc/pve.

services:
HEADER

for n in $(seq 1 "$NODES"); do
    echo ""
    echo "  pve${n}:"
    echo "    devices:"
    echo "      - /dev/fuse:/dev/fuse"
    for i in $(seq 0 $(( PER_NODE - 1 ))); do
        echo "      - ${LINKDIR}/osd-${n}-${i}:/dev/ceph-osd-${i}"
    done
done
